---
abstract: 'load fixture data to storage.'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.720'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-Fixture-DBIC-Schema
no_index:
  directory:
    - inc
    - t
requires:
  DBIx::Class: 0.08008
  Kwalify: 1.16
  Params::Validate: 0.89
  YAML::Syck: 1
version: 0.02
